name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install flake8 mypy bandit detect-secrets
      - name: Lint
        run: |
          flake8 src
      - name: Type check
        run: |
          mypy src
      - name: Security scan
        run: |
          bandit -r src -q || true
          detect-secrets scan > .secrets.baseline || true
      - name: Tests
        run: |
          pytest -q --disable-warnings --maxfail=1
