name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint and type check
        run: |
          pip install flake8 mypy bandit
          flake8 src
          mypy src
          bandit -r src -x tests
      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=agentic_scanner --cov-report=term-missing
